version: 2
jobs:
  test:
    docker:
      - image: circleci/node:8.10
    steps:
      - checkout
      - restore_cache:
          keys:
            - node-modules-{{ checksum "yarn.lock" }}
            - node-modules-
      - run:
          name: Install npm packages
          command: yarn
      - save_cache:
          key: node-modules-{{ checksum "yarn.lock" }}
          paths:
            - node_modules
      - run:
          name: Test
          command: yarn test


workflows:
  version: 2
  test:
    jobs:
      - test
