version: 2
jobs:
  test_and_build:
    docker:
      - image: circleci/node:12.14.0
    steps:
      - checkout
      - restore_cache:
          keys:
            - node-modules-{{ checksum "yarn.lock" }}
            - node-modules-
      - run:
          name: Install npm packages
          command: yarn
      - save_cache:
          key: node-modules-{{ checksum "yarn.lock" }}
          paths:
            - node_modules
      - run:
          name: Test
          command: yarn test
      - run:
          name: Build
          command: yarn build
      - persist_to_workspace:
          root: /home/circleci/project
          paths:
            - dist
  publish:
    docker:
      - image: circleci/node:12.14.0
    steps:
      - checkout
      - run:
          name: Set ~/.npmrc
          command: echo "//registry.npmjs.org/:_authToken=${NPM_TOKEN}" >> ~/.npmrc
      - attach_workspace:
          at: /home/circleci/project
      - run:
          name: Publish if the version hasn't been published
          command: ~/project/bin/publish.sh

workflows:
  version: 2
  master:
    jobs:
      - test_and_build
      - publish:
          requires:
            - test_and_build
          filters:
            branches:
              only:
                - master
  other_blanches:
    jobs:
      - test_and_build:
          filters:
            branches:
              ignore:
                - master
